/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package railwayreservation;

import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Credit_Debit_selection extends javax.swing.JFrame {

    /**
     * Creates new form Credit_Debit_selection
     */
    public Credit_Debit_selection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cardnolbl = new javax.swing.JLabel();
        Cardnotf = new javax.swing.JTextField();
        Cardholderlbl = new javax.swing.JLabel();
        Cardholdertf = new javax.swing.JTextField();
        expirymonthlbl = new javax.swing.JLabel();
        expirymonthtf = new javax.swing.JTextField();
        expiryyearlbl = new javax.swing.JLabel();
        expiryyeartf = new javax.swing.JTextField();
        CVVlbl = new javax.swing.JLabel();
        CVVtf = new javax.swing.JTextField();
        Continuebtn = new javax.swing.JButton();
        Resetbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Cardnolbl.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Cardnolbl.setText("Enter card no:");

        Cardnotf.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        Cardholderlbl.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Cardholderlbl.setText("Enter name of card holder:");

        Cardholdertf.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        expirymonthlbl.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        expirymonthlbl.setText("Enter expiry month:");

        expirymonthtf.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        expiryyearlbl.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        expiryyearlbl.setText("Enter expiry year:");

        expiryyeartf.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        CVVlbl.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        CVVlbl.setText("Enter CVV no:");

        CVVtf.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        Continuebtn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Continuebtn.setText("Continue");
        Continuebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuebtnActionPerformed(evt);
            }
        });

        Resetbtn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Resetbtn.setText("Reset");
        Resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Continuebtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Cardnolbl)
                        .addComponent(Cardholderlbl)
                        .addComponent(expirymonthlbl)
                        .addComponent(expirymonthtf, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CVVlbl)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(expiryyearlbl)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Cardnotf, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addComponent(Cardholdertf))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CVVtf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addComponent(expiryyeartf, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(Resetbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cardnolbl)
                    .addComponent(Cardnotf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cardholderlbl)
                    .addComponent(Cardholdertf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expirymonthlbl)
                    .addComponent(expiryyearlbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expirymonthtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expiryyeartf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CVVlbl)
                    .addComponent(CVVtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Continuebtn)
                    .addComponent(Resetbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetbtnActionPerformed
        Cardnotf.setText("");
        expirymonthtf.setText("");
        Cardholdertf.setText("");
        expiryyeartf.setText("");
        CVVtf.setText(""); 
        Cardnotf.requestFocus();// TODO add your handling code here:
    }//GEN-LAST:event_ResetbtnActionPerformed

    private void ContinuebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinuebtnActionPerformed
      this.dispose();
      JOptionPane.showMessageDialog(null, "Your Tickets have been booked.......Thank You");   // TODO add your handling code here:
    }//GEN-LAST:event_ContinuebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Credit_Debit_selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Credit_Debit_selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Credit_Debit_selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Credit_Debit_selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Credit_Debit_selection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CVVlbl;
    private javax.swing.JTextField CVVtf;
    private javax.swing.JLabel Cardholderlbl;
    private javax.swing.JTextField Cardholdertf;
    private javax.swing.JLabel Cardnolbl;
    private javax.swing.JTextField Cardnotf;
    private javax.swing.JButton Continuebtn;
    private javax.swing.JButton Resetbtn;
    private javax.swing.JLabel expirymonthlbl;
    private javax.swing.JTextField expirymonthtf;
    private javax.swing.JLabel expiryyearlbl;
    private javax.swing.JTextField expiryyeartf;
    // End of variables declaration//GEN-END:variables
}
