/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package railwayreservation;

/**
 *
 * @author Acer
 */
public class Details extends javax.swing.JFrame {
double no;
double final_price;
    /**
     * Creates new form Details
     */
    public Details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        Firstradiobtn = new javax.swing.JRadioButton();
        twotierradiobtn = new javax.swing.JRadioButton();
        sleeperradiobtn = new javax.swing.JRadioButton();
        threetierradiobtn = new javax.swing.JRadioButton();
        upperradiobtn = new javax.swing.JRadioButton();
        middleradiobtn = new javax.swing.JRadioButton();
        lowerradiobtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        payablepricetf = new javax.swing.JTextField();
        Ticketslbl = new javax.swing.JLabel();
        Tickettf = new javax.swing.JTextField();
        Typelbl = new javax.swing.JLabel();
        Typeseatlbl = new javax.swing.JLabel();
        Paymentbtn = new javax.swing.JButton();
        Backbtn = new javax.swing.JButton();
        Selecttypecombobox = new javax.swing.JComboBox<>();
        seattypecombobox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        payablepricelbl = new javax.swing.JLabel();

        jRadioButton2.setText("jRadioButton2");

        jRadioButton1.setText("jRadioButton1");

        jRadioButton5.setText("Third Class");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        Firstradiobtn.setText("First Class");
        Firstradiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstradiobtnActionPerformed(evt);
            }
        });

        twotierradiobtn.setText("Two tier");
        twotierradiobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twotierradiobtnActionPerformed(evt);
            }
        });

        sleeperradiobtn.setText("Sleeper Class");

        threetierradiobtn.setText("Three tier");

        upperradiobtn.setText("Upper");

        middleradiobtn.setText("Middle");

        lowerradiobtn.setText("Lower");

        jLabel1.setText("jLabel1");

        payablepricetf.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        payablepricetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payablepricetfActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Ticketslbl.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Ticketslbl.setText("Enter no. of Tickets:");

        Tickettf.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Tickettf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TickettfActionPerformed(evt);
            }
        });

        Typelbl.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Typelbl.setText("Select Type");

        Typeseatlbl.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Typeseatlbl.setText("Type of Seat");

        Paymentbtn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Paymentbtn.setText("Continue with Payment");
        Paymentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentbtnActionPerformed(evt);
            }
        });

        Backbtn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });

        Selecttypecombobox.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        Selecttypecombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "First Class", "Sleeper Class", "Three tier", "Two tier" }));
        Selecttypecombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecttypecomboboxActionPerformed(evt);
            }
        });

        seattypecombobox.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        seattypecombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Type of Seat", "Lower", "Upper", "Middle", " " }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*Three tier Ticket Price is 300*");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*Two Tier Ticket Price is 400*");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*First Class Ticket Price is 500*");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*Sleeper Class Ticket Price is 200*");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel6.setText("Payable Price is:");

        payablepricelbl.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ticketslbl)
                            .addComponent(seattypecombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Selecttypecombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Typelbl)
                            .addComponent(Typeseatlbl)
                            .addComponent(Paymentbtn)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Tickettf, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(payablepricelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Backbtn))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Ticketslbl)
                    .addComponent(Tickettf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Typelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Selecttypecombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Typeseatlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seattypecombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(payablepricelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Paymentbtn)
                    .addComponent(Backbtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void FirstradiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstradiobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstradiobtnActionPerformed

    private void twotierradiobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twotierradiobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twotierradiobtnActionPerformed

    private void TickettfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TickettfActionPerformed
           // TODO add your handling code here:
            
    }//GEN-LAST:event_TickettfActionPerformed

    private void PaymentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentbtnActionPerformed
        this.dispose();        
        PaymentPortal pp=new PaymentPortal();//It is used for linking the next frame
                pp.setLocationRelativeTo(null);// GUI comes in center
                pp.setTitle("PaymentPortal");
                pp.setSize(600,600);
                pp.setResizable(false);
                pp.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_PaymentbtnActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
       this.dispose();
        SearchTrain st=new SearchTrain();//It is used for linking the next frame
                st.setLocationRelativeTo(null);// GUI comes in center
                st.setTitle("PaymentPortal");
                st.setSize(600,600);
                st.setResizable(false);
                st.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_BackbtnActionPerformed

    private void SelecttypecomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecttypecomboboxActionPerformed
        // TODO add your handling code here:
        String selectedvalue;
        double price;
        selectedvalue = Selecttypecombobox.getSelectedItem().toString();
         no=Integer.parseInt(Tickettf.getText());
         
        if(selectedvalue=="First Class")
        {
            price=500;
            final_price=no*price;
        }
        else if(selectedvalue=="Sleeper Class")
        {
            price=200;
            final_price=no*price;
        }
        else if(selectedvalue=="Two Tier")
        {
            price=400;
            final_price=no*price;
        }
        else if(selectedvalue=="Three Tier")
        {
            price=300;
            final_price=no*price;
           
        }
          String str=Double.toString(final_price);
          payablepricelbl.setText(str);  
    }//GEN-LAST:event_SelecttypecomboboxActionPerformed

    private void payablepricetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payablepricetfActionPerformed
            // TODO add your handling code here:
          
    }//GEN-LAST:event_payablepricetfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JRadioButton Firstradiobtn;
    private javax.swing.JButton Paymentbtn;
    private javax.swing.JComboBox<String> Selecttypecombobox;
    private javax.swing.JLabel Ticketslbl;
    private javax.swing.JTextField Tickettf;
    private javax.swing.JLabel Typelbl;
    private javax.swing.JLabel Typeseatlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton lowerradiobtn;
    private javax.swing.JRadioButton middleradiobtn;
    private javax.swing.JLabel payablepricelbl;
    private javax.swing.JTextField payablepricetf;
    private javax.swing.JComboBox<String> seattypecombobox;
    private javax.swing.JRadioButton sleeperradiobtn;
    private javax.swing.JRadioButton threetierradiobtn;
    private javax.swing.JRadioButton twotierradiobtn;
    private javax.swing.JRadioButton upperradiobtn;
    // End of variables declaration//GEN-END:variables
}
