/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package railwayreservation;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class Signup extends javax.swing.JFrame {
PreparedStatement pst = null;
    Connection con = null;
    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        firstnamelbl = new javax.swing.JLabel();
        lastnamelbl = new javax.swing.JLabel();
        emailidlbl = new javax.swing.JLabel();
        lastname = new javax.swing.JTextField();
        emailid = new javax.swing.JTextField();
        usernanmelbl = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        passwordlbl = new javax.swing.JLabel();
        continuebtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        jTextField4.setText("jTextField4");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        firstname.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        firstnamelbl.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        firstnamelbl.setText("First Name");

        lastnamelbl.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lastnamelbl.setText("Last Name");

        emailidlbl.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        emailidlbl.setText("Email-id");

        lastname.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameActionPerformed(evt);
            }
        });

        emailid.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        usernanmelbl.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        usernanmelbl.setText("Username");

        username.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        password.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        passwordlbl.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        passwordlbl.setText("Password");

        continuebtn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        continuebtn.setText("Continue");
        continuebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuebtnActionPerformed(evt);
            }
        });

        resetbtn.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        resetbtn.setText("Reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(continuebtn)
                .addGap(53, 53, 53)
                .addComponent(resetbtn)
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(firstnamelbl)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lastnamelbl)
                        .addComponent(usernanmelbl)
                        .addComponent(passwordlbl)
                        .addComponent(emailidlbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lastname)
                    .addComponent(firstname, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(emailid)
                    .addComponent(username)
                    .addComponent(password))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnamelbl))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnamelbl)
                    .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailidlbl)
                    .addComponent(emailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernanmelbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continuebtn)
                    .addComponent(resetbtn))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameActionPerformed

    private void continuebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuebtnActionPerformed
                                             
        // TODO add your handling code here:
        
       
        
        try
        {
            String query = "INSERT INTO `login`(`FirstName`, `LastName`, `Emailid`, `Username`, `Password`) VALUES (?,?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/railwayreservation" , "root" , "");
            pst = con.prepareStatement(query);
            pst.setString(1 ,firstname.getText());    
            pst.setString(2 ,lastname.getText());
             
            pst.setString(3 ,emailid.getText()); 
            pst.setString(4 , username.getText()); 
            pst.setString(5 , password.getText());
            /*
            ResultSet rs = pst.executeQuery();
            */
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "You have signed in successfully");
            this.dispose();
            Loginform obj2 = new Loginform();
            obj2.setVisible(true);
            obj2.setTitle("Login Page");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
      
     
    // TODO add your handling code here:
    }//GEN-LAST:event_continuebtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
      username.setText("");
      firstname.setText("");
      lastname.setText("");
      emailid.setText("");
      password.setText("");
      firstname.requestFocus();
    }//GEN-LAST:event_resetbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continuebtn;
    private javax.swing.JTextField emailid;
    private javax.swing.JLabel emailidlbl;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel firstnamelbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField lastname;
    private javax.swing.JLabel lastnamelbl;
    private javax.swing.JTextField password;
    private javax.swing.JLabel passwordlbl;
    private javax.swing.JButton resetbtn;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernanmelbl;
    // End of variables declaration//GEN-END:variables
}
